name: DNS
description: DNS stuff for Hack Club
maintainers: [faisal, graham]
channels:
  - name: dns
    id: CS8TQ86GN
repos:
  - uri: https://github.com/hackclub/dns
    notify: []
resources:
  - name: github
    uri: https://github.com/hackclub/dns
