---
name: Pizza
description: Pizza for everyone!
maintainers: [thomas, arpan, sahiti]
channels:
  - name: pizza-party
    id: C05RZ6K7RS5
    notify: [jasper, sarah]
  - name: pizza-grant-approval
    id: C05RZATA3QR
    notify: [sarah, jasper]
  - name: pizza-grant-renewal
    id: C06HR3TE6TA
    notify: [jasper]
  - name: pizza-pizza
    id: C06H2A574FL
    notify: [jasper]
  - name: pizza-queries
    id: C063JHFQV1S
    notify: [jasper]
  - name: pizza-dev
    id: C06CR1YQQAV
    notify: [jasper]
repos:
  - uri: https://github.com/hackclub/pizza-fund
    notify: [jasper]
sections:
  - name: india
    pattern: india
    notify: [jasper, arpan]
